const STORAGE_KEY="flow-antibody-manager-v1";
const seedData={currentUserId:null,activeView:"dashboard",lab:{name:"Camel Lab 抗体库",returnDays:2,lowStock:25,requireApproval:false},users:[{id:"u-admin",name:"管理员",email:"admin@lab.local",role:"admin",active:true},{id:"u-lin",name:"林同学",email:"lin@lab.local",role:"member",active:true},{id:"u-chen",name:"陈老师",email:"chen@lab.local",role:"admin",active:true}],antibodies:[{id:"ab-cd3",code:"CAMEL-T-001",name:"CD3",clone:"UCHT1",fluor:"FITC",species:"Human",targetGroup:"T细胞",stainingType:"膜表面染色",tags:["T细胞","膜表面染色","人源","常用Panel"],vendor:"BioLegend",catalog:"300406",location:"4C 冰箱 A2",amount:68,threshold:25,status:"available",borrowerId:null,dueDate:null,notes:"T cell panel 常用"},{id:"ab-cd4",code:"CAMEL-T-002",name:"CD4",clone:"RPA-T4",fluor:"PE",species:"Human",targetGroup:"T细胞",stainingType:"膜表面染色",tags:["T细胞","膜表面染色","辅助T细胞"],vendor:"BD",catalog:"555347",location:"4C 冰箱 A2",amount:18,threshold:25,status:"available",borrowerId:null,dueDate:null,notes:"库存偏低"},{id:"ab-cd8",code:"CAMEL-T-003",name:"CD8a",clone:"HIT8a",fluor:"APC",species:"Human",targetGroup:"T细胞",stainingType:"膜表面染色",tags:["T细胞","膜表面染色","杀伤T细胞"],vendor:"BioLegend",catalog:"300912",location:"4C 冰箱 B1",amount:44,threshold:25,status:"checkedOut",borrowerId:"u-lin",dueDate:addDays(new Date(),1),notes:"避光保存"},{id:"ab-live",code:"CAMEL-LIVE-001",name:"Zombie NIR",clone:"-",fluor:"NIR",species:"General",targetGroup:"通用",stainingType:"活死染",tags:["通用","活死染","必备试剂"],vendor:"BioLegend",catalog:"423105",location:"-20C 盒 3",amount:0,threshold:20,status:"empty",borrowerId:null,dueDate:null,notes:"已用完，需采购"}],requests:[{id:"rq-1",antibodyId:"ab-live",requesterId:"u-lin",reason:"死活染用完，下一批样本需要补货",status:"pending",createdAt:new Date().toISOString()}],logs:[{id:"log-1",at:new Date().toISOString(),userId:"u-lin",text:"提交 Zombie NIR 采购申请"},{id:"log-2",at:new Date().toISOString(),userId:"u-lin",text:"取用 CD8a APC，预计明天归还"}]};
let state=loadState();
function addDays(date,days){const next=new Date(date);next.setDate(next.getDate()+days);return next.toISOString().slice(0,10)}
function loadState(){const saved=localStorage.getItem(STORAGE_KEY);try{return normalizeState(saved?JSON.parse(saved):structuredClone(seedData))}catch{return normalizeState(structuredClone(seedData))}}
function normalizeState(data){data.lab={...seedData.lab,...(data.lab||{})};if(data.lab.name==="流式平台抗体库")data.lab.name="Camel Lab 抗体库";data.users=data.users||[];data.antibodies=(data.antibodies||[]).map((item,index)=>({code:`CAMEL-AB-${String(index+1).padStart(3,"0")}`,targetGroup:"未分类",stainingType:"未分类",tags:[],...item,tags:Array.isArray(item.tags)?item.tags:splitTags(item.tags||"")}));data.requests=data.requests||[];data.logs=data.logs||[];return data}
function saveState(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function currentUser(){return state.users.find(user=>user.id===state.currentUserId)}
function isAdmin(){return currentUser()?.role==="admin"}
function userName(id){return state.users.find(user=>user.id===id)?.name||"未指定"}
function antibodyName(id){const item=state.antibodies.find(antibody=>antibody.id===id);return item?`${item.name} ${item.fluor}`:"未知抗体"}
function log(text){state.logs.unshift({id:crypto.randomUUID(),at:new Date().toISOString(),userId:state.currentUserId,text});state.logs=state.logs.slice(0,80)}
function render(){document.querySelector("#app").innerHTML=state.currentUserId?renderShell():renderLogin();bindEvents()}
function renderLogin(){return `<section class="login-shell"><div class="login-panel"><form class="login-card" data-action="login"><div class="brand-mark camel-mark">Camel</div><h1>Camel Lab 流式抗体管理</h1><p class="muted">选择身份并输入姓名后进入系统，所有取用、归还和补货都会记录到个人名下。</p><div class="form-grid"><label>登入身份<select name="role" required><option value="member">学生 / 实验室成员</option><option value="admin">管理员</option></select></label><label>姓名<input name="name" required placeholder="请输入真实姓名" autocomplete="name" /></label><button class="btn" type="submit">登入</button><button class="btn secondary" type="button" data-action="reset-demo">重置演示数据</button></div></form></div><div class="login-visual"><div class="visual-copy"><div class="camel-crest" aria-hidden="true"></div><h1>Camel Lab Antibody Hub</h1><p>让每支抗体都有编号、标签、余量、位置和负责人；在实验开始前就知道它在哪里、够不够用。</p><div class="feature-strip"><div><h3>借还清晰</h3><p>记录取用人、位置和预计归还日期。</p></div><div><h3>标签筛选</h3><p>按T细胞、DC细胞、肿瘤细胞和染色类型快速定位。</p></div><div><h3>权限分层</h3><p>管理员维护库存、成员和采购流程。</p></div></div></div></div></section>`}
function renderShell(){const user=currentUser();const navItems=[["dashboard","总览"],["inventory","抗体库"],["borrowed","取用记录"],["requests","采购申请"],["users","成员权限"],["settings","实验室设置"]];return `<section class="app-shell"><aside class="sidebar"><div class="side-title"><div class="brand-mark">Ab</div><div><strong>${state.lab.name}</strong><div class="muted">${user.name} · ${user.role==="admin"?"管理员":"成员"}</div></div></div><nav class="nav">${navItems.filter(([key])=>isAdmin()||!["users","settings"].includes(key)).map(([key,label])=>`<button class="${state.activeView===key?"active":""}" data-view="${key}" type="button">${label}</button>`).join("")}</nav><div class="side-foot"><p>今日建议：使用前先登记，低于阈值立即申请补货。</p><button class="btn secondary" data-action="logout" type="button">登出</button></div></aside><section class="main">${renderView()}</section></section><div id="modal-root"></div>`}
function renderView(){return({dashboard:renderDashboard,inventory:renderInventory,borrowed:renderBorrowed,requests:renderRequests,users:renderUsers,settings:renderSettings}[state.activeView]||renderDashboard)()}
function renderTopbar(title,subtitle,action){return `<div class="topbar"><div><h1>${title}</h1><p class="muted">${subtitle}</p></div><div class="button-row">${action}</div></div>`}
function renderDashboard(){const total=state.antibodies.length,borrowed=state.antibodies.filter(item=>item.status==="checkedOut").length,low=state.antibodies.filter(item=>item.amount<=item.threshold).length,pending=state.requests.filter(request=>request.status==="pending").length,attention=state.antibodies.filter(item=>item.status!=="available"||item.amount<=item.threshold);return `${renderTopbar("总览","快速查看抗体状态、归还风险和待处理事项。",isAdmin()?`<button class="btn" data-modal="antibody">新增抗体</button>`:"")}<div class="metrics"><div class="metric"><strong>${total}</strong><span class="muted">抗体总数</span></div><div class="metric"><strong>${borrowed}</strong><span class="muted">正在取用</span></div><div class="metric"><strong>${low}</strong><span class="muted">低库存/用完</span></div><div class="metric"><strong>${pending}</strong><span class="muted">待处理采购</span></div></div><div class="content-grid"><div class="panel"><h2>需要关注</h2><div class="cards-grid">${attention.length?attention.map(renderAntibodyCard).join(""):`<div class="empty-state">暂无需要关注的抗体</div>`}</div></div><div class="panel"><h2>最近动态</h2><div class="list">${state.logs.slice(0,8).map(renderLog).join("")}</div></div></div>`}
function renderInventory(){const fluorOptions=[...new Set(state.antibodies.map(item=>item.fluor))].sort(),groupOptions=[...new Set(state.antibodies.map(item=>item.targetGroup).filter(Boolean))].sort(),tagOptions=[...new Set(state.antibodies.flatMap(item=>item.tags||[]))].sort();return `${renderTopbar("抗体库","搜索、筛选和维护所有流式抗体。",isAdmin()?`<button class="btn" data-modal="antibody">新增抗体</button>`:"")}<div class="toolbar"><input placeholder="搜索编号、名称、荧光、货号、位置、标签" data-filter="query" value="${state.filterQuery||""}" /><select data-filter="fluor"><option value="">全部荧光</option>${fluorOptions.map(fluor=>`<option ${state.filterFluor===fluor?"selected":""}>${fluor}</option>`).join("")}</select><select data-filter="group"><option value="">全部分类</option>${groupOptions.map(group=>`<option ${state.filterGroup===group?"selected":""}>${group}</option>`).join("")}</select><select data-filter="tag"><option value="">全部标签</option>${tagOptions.map(tag=>`<option ${state.filterTag===tag?"selected":""}>${tag}</option>`).join("")}</select><select data-filter="status"><option value="">全部状态</option><option value="available" ${state.filterStatus==="available"?"selected":""}>可用</option><option value="checkedOut" ${state.filterStatus==="checkedOut"?"selected":""}>已取用</option><option value="empty" ${state.filterStatus==="empty"?"selected":""}>已用完</option></select><button class="btn secondary" data-action="clear-filter" type="button">清除</button></div><div class="cards-grid">${filteredAntibodies().map(renderAntibodyCard).join("")||`<div class="empty-state">没有匹配的抗体</div>`}</div>`}
function renderBorrowed(){const rows=state.antibodies.filter(item=>item.status==="checkedOut");return `${renderTopbar("取用记录","查看当前未归还的抗体。","")}<div class="panel table-wrap"><table><thead><tr><th>抗体</th><th>取用人</th><th>预计归还</th><th>位置</th><th>状态</th><th>操作</th></tr></thead><tbody>${rows.map(item=>`<tr><td><strong>${item.name}</strong><br><span class="muted">${item.clone} · ${item.fluor}</span></td><td>${userName(item.borrowerId)}</td><td>${item.dueDate||"未填写"}</td><td>${item.location}</td><td>${statusTag(item)}</td><td>${canManageItem(item)?`<button class="btn secondary" data-action="return" data-id="${item.id}">归还</button>`:""}</td></tr>`).join("")||`<tr><td colspan="6">暂无未归还抗体</td></tr>`}</tbody></table></div>`}
function renderRequests(){return `${renderTopbar("采购申请","低库存、用完或新增需求都可以在这里登记。",`<button class="btn" data-modal="request">新建申请</button>`)}<div class="list">${state.requests.map(request=>`<div class="list-row"><div><strong>${antibodyName(request.antibodyId)}</strong><p class="muted">${request.reason}</p><span class="tag ${request.status==="approved"?"ok":request.status==="rejected"?"bad":"warn"}">${requestStatus(request.status)}</span><span class="muted"> ${userName(request.requesterId)} · ${new Date(request.createdAt).toLocaleString("zh-CN")}</span></div>${isAdmin()&&request.status==="pending"?`<div class="button-row"><button class="btn" data-action="approve-request" data-id="${request.id}">批准</button><button class="btn secondary" data-action="reject-request" data-id="${request.id}">驳回</button></div>`:""}</div>`).join("")||`<div class="empty-state">暂无采购申请</div>`}</div>`}
function renderUsers(){if(!isAdmin())return renderDashboard();return `${renderTopbar("成员权限","维护成员账号和管理员权限。",`<button class="btn" data-modal="user">新增成员</button>`)}<div class="panel table-wrap"><table><thead><tr><th>姓名</th><th>邮箱</th><th>角色</th><th>状态</th><th>操作</th></tr></thead><tbody>${state.users.map(user=>`<tr><td><strong>${user.name}</strong></td><td>${user.email}</td><td>${user.role==="admin"?"管理员":"成员"}</td><td>${user.active?"启用":"停用"}</td><td><button class="btn secondary" data-action="toggle-role" data-id="${user.id}">切换角色</button> <button class="btn ghost" data-action="toggle-active" data-id="${user.id}">${user.active?"停用":"启用"}</button></td></tr>`).join("")}</tbody></table></div>`}
function renderSettings(){if(!isAdmin())return renderDashboard();return `${renderTopbar("实验室设置","设置默认规则和自定义阈值。","")}<form class="panel form-grid" data-action="save-settings"><label>实验室/课题组名称<input name="name" value="${state.lab.name}" /></label><label>默认归还天数<input name="returnDays" type="number" min="1" max="30" value="${state.lab.returnDays}" /></label><label>默认低库存阈值（百分比）<input name="lowStock" type="number" min="1" max="90" value="${state.lab.lowStock}" /></label><label>采购申请是否需要管理员审批<select name="requireApproval"><option value="false" ${!state.lab.requireApproval?"selected":""}>不强制，先登记再处理</option><option value="true" ${state.lab.requireApproval?"selected":""}>需要管理员批准</option></select></label><div class="button-row"><button class="btn" type="submit">保存设置</button></div></form>`}
function filteredAntibodies(){const query=(state.filterQuery||"").trim().toLowerCase();return state.antibodies.filter(item=>{const tags=item.tags||[],text=[item.code,item.name,item.clone,item.fluor,item.vendor,item.catalog,item.location,item.targetGroup,item.stainingType,...tags,item.notes].join(" ").toLowerCase();return(!query||text.includes(query))&&(!state.filterFluor||item.fluor===state.filterFluor)&&(!state.filterGroup||item.targetGroup===state.filterGroup)&&(!state.filterTag||tags.includes(state.filterTag))&&(!state.filterStatus||item.status===state.filterStatus)})}
function statusTag(item){if(item.status==="empty")return `<span class="tag bad">已用完</span>`;if(item.status==="checkedOut")return `<span class="tag warn">已取用</span>`;if(item.amount<=item.threshold)return `<span class="tag warn">低库存</span>`;return `<span class="tag ok">可用</span>`}
function requestStatus(status){return{pending:"待处理",approved:"已批准",rejected:"已驳回"}[status]||status}
function renderAntibodyCard(item){const level=Math.max(0,Math.min(100,Number(item.amount)||0)),fillClass=level===0?"empty":level<=item.threshold?"low":"",actions=[];if(item.status==="available"&&item.amount>0)actions.push(`<button class="btn" data-action="checkout" data-id="${item.id}">取用</button>`);if(canManageItem(item)&&item.status==="checkedOut")actions.push(`<button class="btn secondary" data-action="return" data-id="${item.id}">归还</button>`);actions.push(`<button class="btn secondary" data-action="mark-empty" data-id="${item.id}">用完</button>`);actions.push(`<button class="btn ghost" data-action="request-stock" data-id="${item.id}">补货</button>`);if(isAdmin())actions.push(`<button class="btn ghost" data-modal="antibody" data-id="${item.id}">编辑</button>`);return `<article class="antibody-card"><div class="card-head"><div><h3>${item.name} <span class="muted">${item.fluor}</span></h3><div class="muted">${item.code||"未编号"} · ${item.clone} · ${item.species}</div></div>${statusTag(item)}</div><div class="tag-row"><span class="tag">${item.targetGroup||"未分类"}</span><span class="tag">${item.stainingType||"未分类"}</span>${(item.tags||[]).map(tag=>`<span class="tag soft">${tag}</span>`).join("")}</div><div class="meta"><span>厂商：${item.vendor}</span><span>货号：${item.catalog}</span><span>位置：${item.location}</span><span>取用人：${item.borrowerId?userName(item.borrowerId):"无"}</span></div><div><div class="muted">余量 ${level}% · 阈值 ${item.threshold}%</div><div class="progress"><span class="${fillClass}" style="width:${level}%"></span></div></div><p class="muted">${item.notes||"暂无备注"}</p><div class="button-row">${actions.join("")}</div></article>`}
function renderLog(entry){return `<div class="timeline-row"><strong>${entry.text}</strong><div class="muted">${userName(entry.userId)} · ${new Date(entry.at).toLocaleString("zh-CN")}</div></div>`}
function canManageItem(item){return isAdmin()||item.borrowerId===state.currentUserId}
function bindEvents(){document.querySelectorAll("[data-view]").forEach(button=>button.addEventListener("click",()=>{state.activeView=button.dataset.view;saveState();render()}));document.querySelectorAll("[data-action]").forEach(element=>element.addEventListener("click",handleAction));document.querySelectorAll("form[data-action]").forEach(form=>form.addEventListener("submit",handleSubmit));document.querySelectorAll("[data-modal]").forEach(button=>button.addEventListener("click",()=>openModal(button.dataset.modal,button.dataset.id)));document.querySelectorAll("[data-filter]").forEach(field=>field.addEventListener("input",()=>{state[`filter${capitalize(field.dataset.filter)}`]=field.value;saveState();render()}))}
function handleSubmit(event){event.preventDefault();const form=event.currentTarget,data=Object.fromEntries(new FormData(form).entries());if(form.dataset.action==="login"){const name=data.name.trim();if(!name)return;let user=state.users.find(item=>item.active&&item.name===name&&item.role===data.role);if(!user){user={id:crypto.randomUUID(),name,email:`${name.replace(/\s+/g,"").toLowerCase()}@camel.lab`,role:data.role,active:true};state.users.push(user)}state.currentUserId=user.id;log(`${data.role==="admin"?"管理员":"成员"} ${name} 登入系统`)}if(form.dataset.action==="save-settings"){state.lab={name:data.name,returnDays:Number(data.returnDays),lowStock:Number(data.lowStock),requireApproval:data.requireApproval==="true"};log("更新实验室设置")}saveState();render()}
function handleAction(event){const action=event.currentTarget.dataset.action,id=event.currentTarget.dataset.id;if(["login","save-settings"].includes(action))return;if(action==="logout")state.currentUserId=null;if(action==="reset-demo"){state=structuredClone(seedData);localStorage.removeItem(STORAGE_KEY)}if(action==="clear-filter"){state.filterQuery="";state.filterFluor="";state.filterGroup="";state.filterTag="";state.filterStatus=""}if(action==="checkout")checkoutAntibody(id);if(action==="return")returnAntibody(id);if(action==="mark-empty")markEmpty(id);if(action==="request-stock"){openModal("request",id);return}if(action==="approve-request")updateRequest(id,"approved");if(action==="reject-request")updateRequest(id,"rejected");if(action==="toggle-role")toggleRole(id);if(action==="toggle-active")toggleActive(id);saveState();render()}
function checkoutAntibody(id){const item=state.antibodies.find(antibody=>antibody.id===id);if(!item)return;item.status="checkedOut";item.borrowerId=state.currentUserId;item.dueDate=addDays(new Date(),state.lab.returnDays);log(`取用 ${item.name} ${item.fluor}`)}
function returnAntibody(id){const item=state.antibodies.find(antibody=>antibody.id===id);if(!item)return;item.status=item.amount>0?"available":"empty";item.borrowerId=null;item.dueDate=null;log(`归还 ${item.name} ${item.fluor}`)}
function markEmpty(id){const item=state.antibodies.find(antibody=>antibody.id===id);if(!item)return;item.amount=0;item.status="empty";item.borrowerId=null;item.dueDate=null;log(`标记 ${item.name} ${item.fluor} 已用完`)}
function updateRequest(id,status){const request=state.requests.find(item=>item.id===id);if(!request)return;request.status=status;log(`${requestStatus(status)} ${antibodyName(request.antibodyId)} 的采购申请`)}
function toggleRole(id){const user=state.users.find(item=>item.id===id);if(!user)return;user.role=user.role==="admin"?"member":"admin";log(`调整 ${user.name} 为${user.role==="admin"?"管理员":"成员"}`)}
function toggleActive(id){const user=state.users.find(item=>item.id===id);if(!user||user.id===state.currentUserId)return;user.active=!user.active;log(`${user.active?"启用":"停用"} ${user.name}`)}
function openModal(type,id=""){const root=document.querySelector("#modal-root");root.innerHTML=`<div class="modal"><div class="modal-card">${modalContent(type,id)}</div></div>`;root.querySelector(".modal").addEventListener("click",event=>{if(event.target.className==="modal")closeModal()});root.querySelectorAll("[data-close]").forEach(button=>button.addEventListener("click",closeModal));root.querySelectorAll("form").forEach(form=>form.addEventListener("submit",handleModalSubmit))}
function closeModal(){document.querySelector("#modal-root").innerHTML=""}
function modalContent(type,id){if(type==="antibody")return antibodyForm(id);if(type==="request")return requestForm(id);if(type==="user")return userForm();return""}
function antibodyForm(id){const item=state.antibodies.find(antibody=>antibody.id===id)||{id:"",code:"",name:"",clone:"",fluor:"",species:"",targetGroup:"T细胞",stainingType:"膜表面染色",tags:[],vendor:"",catalog:"",location:"",amount:100,threshold:state.lab.lowStock,status:"available",notes:""};return `<h2>${id?"编辑抗体":"新增抗体"}</h2><form class="form-grid" data-modal-submit="antibody"><input type="hidden" name="id" value="${item.id}" /><label>抗体编号<input name="code" required value="${item.code||""}" placeholder="例如 CAMEL-T-004" /></label><label>抗体名称<input name="name" required value="${item.name}" /></label><label>Clone<input name="clone" value="${item.clone}" /></label><label>荧光标记<input name="fluor" required value="${item.fluor}" /></label><label>物种/用途<input name="species" value="${item.species}" /></label><label>细胞分类<select name="targetGroup">${["T细胞","B细胞","DC细胞","髓系细胞","肿瘤细胞","通用","其他"].map(group=>`<option value="${group}" ${item.targetGroup===group?"selected":""}>${group}</option>`).join("")}</select></label><label>染色类型<select name="stainingType">${["膜表面染色","胞内染色","核内染色","活死染","二抗/同型对照","其他"].map(type=>`<option value="${type}" ${item.stainingType===type?"selected":""}>${type}</option>`).join("")}</select></label><label>自定义标签<input name="tags" value="${(item.tags||[]).join(", ")}" placeholder="例如 Panel A, 人源, 常用" /></label><label>厂商<input name="vendor" value="${item.vendor}" /></label><label>货号<input name="catalog" value="${item.catalog}" /></label><label>存放位置<input name="location" required value="${item.location}" /></label><label>当前余量（百分比）<input name="amount" type="number" min="0" max="100" value="${item.amount}" /></label><label>提醒阈值（百分比）<input name="threshold" type="number" min="1" max="90" value="${item.threshold}" /></label><label>备注<textarea name="notes">${item.notes}</textarea></label><div class="button-row"><button class="btn" type="submit">保存</button><button class="btn secondary" data-close type="button">取消</button></div></form>`}
function requestForm(id){const options=state.antibodies.map(item=>`<option value="${item.id}" ${id===item.id?"selected":""}>${item.name} ${item.fluor}</option>`).join("");return `<h2>采购申请</h2><form class="form-grid" data-modal-submit="request"><label>抗体<select name="antibodyId">${options}</select></label><label>申请原因<textarea name="reason" required placeholder="例如：余量不足、已用完、下周实验需要..."></textarea></label><div class="button-row"><button class="btn" type="submit">提交</button><button class="btn secondary" data-close type="button">取消</button></div></form>`}
function userForm(){return `<h2>新增成员</h2><form class="form-grid" data-modal-submit="user"><label>姓名<input name="name" required /></label><label>邮箱<input name="email" type="email" required /></label><label>角色<select name="role"><option value="member">成员</option><option value="admin">管理员</option></select></label><div class="button-row"><button class="btn" type="submit">保存</button><button class="btn secondary" data-close type="button">取消</button></div></form>`}
function handleModalSubmit(event){event.preventDefault();const form=event.currentTarget,data=Object.fromEntries(new FormData(form).entries());if(form.dataset.modalSubmit==="antibody")saveAntibody(data);if(form.dataset.modalSubmit==="request")saveRequest(data);if(form.dataset.modalSubmit==="user")saveUser(data);saveState();closeModal();render()}
function saveAntibody(data){const tags=uniqueTags([data.targetGroup,data.stainingType,...splitTags(data.tags)]),item={...data,tags,amount:Number(data.amount),threshold:Number(data.threshold),status:Number(data.amount)<=0?"empty":"available",borrowerId:null,dueDate:null};if(data.id){const index=state.antibodies.findIndex(antibody=>antibody.id===data.id);state.antibodies[index]={...state.antibodies[index],...item};log(`更新 ${item.name} ${item.fluor}`)}else{item.id=crypto.randomUUID();state.antibodies.unshift(item);log(`新增 ${item.name} ${item.fluor}`)}}
function saveRequest(data){state.requests.unshift({id:crypto.randomUUID(),antibodyId:data.antibodyId,requesterId:state.currentUserId,reason:data.reason,status:"pending",createdAt:new Date().toISOString()});log(`提交 ${antibodyName(data.antibodyId)} 采购申请`)}
function saveUser(data){state.users.push({id:crypto.randomUUID(),name:data.name,email:data.email,role:data.role,active:true});log(`新增成员 ${data.name}`)}
function capitalize(text){return text.charAt(0).toUpperCase()+text.slice(1)}
function splitTags(value){return String(value||"").split(/[,，;；\s]+/).map(tag=>tag.trim()).filter(Boolean)}
function uniqueTags(tags){return[...new Set(tags.filter(Boolean))]}
render();
